### ISSUE TITLE
Installation échec.

### ISSUE THREAD

**Issue by Jeanpierregi** [r-e-d/correctfrBG2EE#225]
Bonjour à tous,

Je suis sans doute idiot, mais après avoir téléchargé le "correctfrBG2EE-master", et avoir trouvé un weidu.exe que j'ai renommé en setup-correctfrbg2ee.exe pour lancer l'installation (avec le setup dans le dossier de BG2 directement), j'ai eu le setup suivant en erreur: (voir pièce jointe)

Je me doute que j'ai fait une erreur quelque part, mais je comprends absolument pas où ...
[SETUP-CORRECTFRBG2EE.txt](https://github.com/r-e-d/correctfrBG2EE/files/8791507/SETUP-CORRECTFRBG2EE.txt)

Si une bonne âme avait une explication pour m'aider à l'installer, je la remercie!

**Comment by GwendolyneFreddy** [comment]
Le fichier bg2ee.tph manque dans le dépôt. Pour installer le mod, télécharge la version officielle : https://github.com/r-e-d/correctfrBG2EE/releases/tag/0.11

**Comment by r-e-d** [comment]
Je confirme, certains des fichiers nécessaires pour l'installation sont générés automatiquement lors des releases, il faut donc obligatoirement prendre le zip de la release et ne pas prendre la version master.

**Comment by r-e-d** [comment]
Il y a maintenant un message d'erreur plus précis quand on essai d'installer la version master.
